---

blank_issues_enabled: false
contact_links:
  - name: "Diskutoj kaj Demandoj"
    url: "https://github.com/orgs/esperantigo/discussions"
    about: |
      Bonvolu demandi kaj respondi demandojn ĉi tie.
